import { playlist } from '@/data/playlist';
import type { Track } from '@/types/content';
const STORAGE_KEY = 'hatrix-player';
export type PlaybackMode = 'sequence' | 'shuffle' | 'single';
interface PlayerPreferences { volume:number; expanded:boolean; mode:PlaybackMode; index:number }
const modes: PlaybackMode[] = ['sequence','shuffle','single'];
export function nextMode(mode: PlaybackMode): PlaybackMode { return modes[(modes.indexOf(mode)+1)%3] ?? 'sequence'; }
function prefs(): PlayerPreferences { try { const s=JSON.parse(localStorage.getItem(STORAGE_KEY)??'{}') as Partial<PlayerPreferences>; return {volume:typeof s.volume==='number'?Math.max(0,Math.min(1,s.volume)):.7,expanded:s.expanded!==false,mode:modes.includes(s.mode as PlaybackMode)?s.mode as PlaybackMode:'sequence',index:Number.isInteger(s.index)?Math.max(0,s.index as number):0}; } catch { return {volume:.7,expanded:true,mode:'sequence',index:0}; } }
const save=(p:PlayerPreferences)=>localStorage.setItem(STORAGE_KEY,JSON.stringify(p));
const fmt=(n:number)=>Number.isFinite(n)&&n>=0?`${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`:'0:00';
export function initializeMusicPlayer(tracks: readonly Track[] = playlist, root: Document = document): HTMLAudioElement|undefined {
 const player=root.querySelector<HTMLElement>('[data-music-player]'); const volume=player?.querySelector<HTMLInputElement>('[data-player-volume]'); if(!player||!volume)return;
 const p=prefs(); volume.value=String(p.volume); player.dataset.uiState=p.expanded?'expanded':'collapsed'; if(player.dataset.bound==='true') return; player.dataset.bound='true';
 volume.addEventListener('input',()=>{const q=prefs();q.volume=Number(volume.value);save(q)});
 const fold=player.querySelector<HTMLButtonElement>('[data-player-fold]'); if(player.dataset.contentPage!=='true') player.dataset.uiState='expanded'; fold?.addEventListener('click',()=>{const open=player.dataset.uiState!=='collapsed';player.dataset.uiState=open?'collapsed':'expanded';fold.setAttribute('aria-expanded',String(!open));fold.textContent=open?'展开':'收起';save({...prefs(),expanded:!open})}); root.addEventListener('keydown',e=>{if(e.key==='Escape'&&player.dataset.contentPage==='true'&&player.dataset.uiState==='expanded'){player.dataset.uiState='collapsed';fold?.setAttribute('aria-expanded','false');if(fold)fold.textContent='展开';save({...prefs(),expanded:false})}});
 if(!tracks.length)return; const title=player.querySelector<HTMLElement>('[data-player-title]'),artist=player.querySelector<HTMLElement>('[data-player-artist]'),play=player.querySelector<HTMLButtonElement>('[data-player-play]'),prev=player.querySelector<HTMLButtonElement>('[data-player-prev]'),next=player.querySelector<HTMLButtonElement>('[data-player-next]'),modeBtn=player.querySelector<HTMLButtonElement>('[data-player-mode]'),progress=player.querySelector<HTMLInputElement>('[data-player-progress]'),time=player.querySelector<HTMLElement>('[data-player-time]'); let i=Math.min(p.index,tracks.length-1),mode=p.mode; const audio=new Audio();audio.volume=p.volume;
 const label=()=>mode==='shuffle'?'随机':mode==='single'?'单曲':'顺序'; const render=()=>{const t=tracks[i];if(!t)return;audio.src=t.src;if(title)title.textContent=t.title;if(artist)artist.textContent=t.artist;if(modeBtn){modeBtn.textContent=label();modeBtn.setAttribute('aria-label',`播放模式：${label()}播放`)}save({...prefs(),index:i,mode})}; const select=(d:number)=>{i=mode==='shuffle'?Math.floor(Math.random()*tracks.length):(i+d+tracks.length)%tracks.length;render();audio.play().catch(()=>undefined)};
 play?.addEventListener('click',()=>audio.paused?audio.play().catch(()=>undefined):audio.pause());prev?.addEventListener('click',()=>select(-1));next?.addEventListener('click',()=>select(1));modeBtn?.addEventListener('click',()=>{mode=nextMode(mode);render()});volume.addEventListener('input',()=>audio.volume=Number(volume.value));progress?.addEventListener('input',()=>{if(audio.duration)audio.currentTime=Number(progress.value)*audio.duration});audio.addEventListener('play',()=>{player.dataset.playbackState='playing';if(play)play.textContent='⏸'});audio.addEventListener('pause',()=>{player.dataset.playbackState='paused';if(play)play.textContent='▶'});audio.addEventListener('timeupdate',()=>{const r=audio.duration?audio.currentTime/audio.duration:0;if(progress)progress.value=String(r);if(time)time.textContent=`${fmt(audio.currentTime)} / ${fmt(audio.duration)}`});audio.addEventListener('loadedmetadata',()=>{if(time)time.textContent=`0:00 / ${fmt(audio.duration)}`});audio.addEventListener('ended',()=>mode==='single'?(audio.currentTime=0,audio.play().catch(()=>undefined)):select(1));audio.addEventListener('error',()=>player.dataset.playbackState='error');render();return audio;
}
document.addEventListener('astro:page-load',()=>initializeMusicPlayer()); initializeMusicPlayer();
