import { playlist } from '@/data/playlist';
import type { Track } from '@/types/content';
const STORAGE_KEY = 'hatrix-player';
export type PlaybackMode = 'list' | 'shuffle' | 'single';
interface PlayerPreferences { volume:number; mode:PlaybackMode; index:number }
const modes: PlaybackMode[] = ['list','shuffle','single'];
export function nextMode(mode: PlaybackMode): PlaybackMode { return modes[(modes.indexOf(mode)+1)%modes.length] ?? 'list'; }
function readPreferences(): PlayerPreferences { try { const s=JSON.parse(localStorage.getItem(STORAGE_KEY)??'{}') as Partial<PlayerPreferences>; const storedMode=s.mode as PlaybackMode | 'sequence' | undefined; const mode=storedMode==='sequence'?'list':storedMode; return {volume:typeof s.volume==='number'?Math.max(0,Math.min(1,s.volume)):.7,mode:modes.includes(mode as PlaybackMode)?mode as PlaybackMode:'list',index:Number.isInteger(s.index)?Math.max(0,s.index as number):0}; } catch { return {volume:.7,mode:'list',index:0}; } }
const save=(p:PlayerPreferences)=>localStorage.setItem(STORAGE_KEY,JSON.stringify(p));
export function initializeMusicPlayer(tracks: readonly Track[] = playlist, root: Document = document): HTMLAudioElement|undefined { const player=root.querySelector<HTMLElement>('[data-music-player]'); const volume=player?.querySelector<HTMLInputElement>('[data-player-volume]'); if(!player||!volume||player.dataset.bound==='true')return; player.dataset.bound='true'; const p=readPreferences(); volume.value=String(p.volume); if(!tracks.length)return; let i=Math.min(p.index,tracks.length-1),mode=p.mode; const play=player.querySelector<HTMLButtonElement>('[data-player-play]'),prev=player.querySelector<HTMLButtonElement>('[data-player-prev]'),next=player.querySelector<HTMLButtonElement>('[data-player-next]'),modeBtn=player.querySelector<HTMLButtonElement>('[data-player-mode]'),title=player.querySelector<HTMLElement>('[data-player-title]'),artist=player.querySelector<HTMLElement>('[data-player-artist]'); const audio=new Audio(); audio.volume=p.volume; const render=()=>{const t=tracks[i];if(!t)return;audio.src=t.src;if(title)title.textContent=t.title;if(artist)artist.textContent=t.artist;if(modeBtn){modeBtn.dataset.mode=mode;modeBtn.setAttribute('aria-label',`播放模式：${mode==='shuffle'?'随机播放':mode==='single'?'单曲循环':'列表循环'}`)}save({volume:Number(volume.value),mode,index:i})}; const select=(d:number)=>{i=mode==='shuffle'?Math.floor(Math.random()*tracks.length):(i+d+tracks.length)%tracks.length;render();audio.play().catch(()=>undefined)}; volume.addEventListener('input',()=>{audio.volume=Number(volume.value);save({...readPreferences(),volume:audio.volume})}); volume.addEventListener('wheel',e=>{e.preventDefault();const nextValue=Math.max(0,Math.min(1,Number(volume.value)-(e.deltaY>0?.04:-.04)));volume.value=String(nextValue);volume.dispatchEvent(new Event('input',{bubbles:true}))},{passive:false}); play?.addEventListener('click',()=>audio.paused?audio.play().catch(()=>undefined):audio.pause()); prev?.addEventListener('click',()=>select(-1)); next?.addEventListener('click',()=>select(1)); modeBtn?.addEventListener('click',()=>{mode=nextMode(mode);render()}); audio.addEventListener('play',()=>{player.dataset.playbackState='playing';if(play){play.textContent='⏸';play.setAttribute('aria-label','暂停')}}); audio.addEventListener('pause',()=>{player.dataset.playbackState='paused';if(play){play.textContent='▶';play.setAttribute('aria-label','播放')}}); audio.addEventListener('ended',()=>mode==='single'?(audio.currentTime=0,audio.play().catch(()=>undefined)):select(1)); audio.addEventListener('error',()=>player.dataset.playbackState='error'); render(); return audio; }
document.addEventListener('astro:page-load',()=>initializeMusicPlayer()); initializeMusicPlayer();


